import os
import random
import pandas as pd
import yaml
import subprocess
import datetime as datetime

class HyperParameterTuner:
    def __init__(self):
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        self.root = os.path.dirname(self.script_dir)
        self.config_dir = os.path.join(self.root, "config")
        os.makedirs(self.config_dir, exist_ok=True)

        self.results = []
        self.best_config = None
        self.min_g_loss = float('inf')

    def run_experiment(self, params, name):
        tuning_epochs = 1
        temp_file_name = f"temp_tuner_{name}.yaml"
        temp_file_path = os.path.join(self.config_dir, temp_file_name)
        base_path = os.path.join(self.config_dir, 'improved_config.yaml')
        with open(base_path, 'r') as f:
            config = yaml.safe_load(f)

        config['project_name'] = name
        config['trainer'].update({
            'lr_g': params['lr'],
            'lr_d': params['lr'],
            'beta1': params['beta1'],
            'beta2': params['beta2'],
            'epochs': tuning_epochs
        })
        config['model'].update({
            'leaky_slope': params['leaky_slope'],
            'latent_dim': params['latent_dim'],
            'generator_channels': params['g_channels'],
            'discriminator_channels': params['d_channels']
        })
        config['logger']['log_dir'] = f"results/tuning/{name}/logs"
        try:

            with open(temp_file_path ,'w') as f:
                yaml.dump(config, f)
                print(f"\n[Tuner] Running: {name} | Params: {params}")
                subprocess.run(["python", "main.py", "--config", temp_file_path], cwd=self.root)

                # 3. Collect Results (Read the CSV generated by main.py)
                csv_path = os.path.join(self.root, config['logger']['log_dir'], 'history.csv')
                if os.path.exists(csv_path):
                    df = pd.read_csv(csv_path)
                    # We evaluate "best" based on the final epoch's generator loss or stability
                    final_g_loss = df['loss_g'].iloc[-1]
                    params['final_g_loss'] = final_g_loss
                    self.results.append(params)

                    if final_g_loss < self.min_g_loss:
                        self.min_g_loss = final_g_loss
                        self.best_config = params
        finally:
            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)
    def print_summary(self):
        print("\n" + "=" * 50)
        print("TUNING SUMMARY")
        print("=" * 50)
        for i, res in enumerate(self.results):
            print(
                f"Trial {i}: G_Loss: {res.get('final_g_loss', 'N/A'):.4f} | LR: {res['lr']} | Slope: {res['leaky_slope']}")

        if self.best_config:
            print("\n>>> BEST CONFIGURATION FOUND:")
            print(self.best_config)
        print("=" * 50)

    def grid_search(self):

        lrs = [0.00001, 0.0001, 0.0002, 0.001]  # 10^-5 to 10^-3
        dim_pairs = [(100,50) , (500,100), (1000, 150), (1500,200)]
        architectures = {
            "shallow": {"g": [256, 128, 64], "d": [64, 128, 256]},
            "standard": {"g": [512, 256, 128, 64], "d": [64, 128, 256, 512]},
            "deep": {"g": [1024, 512, 256, 128, 64], "d": [64, 128, 256, 512, 1024]}
        }
        '''
        # Uncomment this to test locally
        lrs = [0.00001]
        dim_pairs = [(100,50)]
        architectures = {
            "shallow": {"g": [256, 128, 64], "d": [64, 128, 256]}
        }
        '''
        for arch_name, channels in architectures.items():
            for lr in lrs:
                for l_dim, e_dim in dim_pairs:
                    params = self._get_default_params()
                    params.update({
                        'lr': lr,
                        'latent_dim': l_dim,
                        'embedding_dim': e_dim,
                        'g_channels': channels['g'],
                        'd_channels': channels['d'],
                        'leaky_slope': 0.2,
                        'beta1': 0.5
                    })

                    name = f"grid_{arch_name}_lr{lr}_cap{l_dim}_{e_dim}"
                    self.run_experiment(params, name)

    def random_search(self, num_trials=5):
        print(f"\n>>> Starting Random Search with {num_trials} trials...")

        # Define some architectural variations to sample from
        channel_options = [
            # Standard [512, 256, 128, 64]
            {'g': [512, 256, 128, 64], 'd': [64, 128, 256, 512]},
            # Slimmer [256, 128, 64, 32]
            {'g': [256, 128, 64, 32], 'd': [32, 64, 128, 256]},
            # Deeper/Wider middle layers
            {'g': [1024, 512, 256, 128], 'd': [128, 256, 512, 1024]}
        ]

        for i in range(num_trials):
            # Sample using Log-Uniform for LR (crucial for finding order of magnitude)
            lr = 10 ** random.uniform(-5, -3)  # Range: 0.00001 to 0.001

            arch = random.choice(channel_options)

            params = {
                'lr': lr,
                'beta1': random.uniform(0.1, 0.9),  # Wide range for momentum
                'beta2': random.uniform(0.9, 0.999),
                'leaky_slope': random.uniform(0.01, 0.3),  # From almost zero to very leaky
                'latent_dim': random.choice([64, 100, 128, 256]),
                'g_channels': arch['g'],
                'd_channels': arch['d']
            }

            trial_name = f"random_trial_{i}_lr{lr:.6f}_slope{params['leaky_slope']:.2f}"

            self.run_experiment(params, trial_name)

    def _get_default_params(self):
        return {
            'lr': 0.0002, 'beta1': 0.5, 'beta2': 0.999,
            'leaky_slope': 0.2, 'latent_dim': 100,
            'g_channels': [512, 256, 128, 64], 'd_channels': [64, 128, 256, 512]
        }
    def save_best_config(self, target_config_name = "improved_config.yaml"):
        if not self.best_config:
            print("No best configuration found to save.")
            return

        target_path = os.path.join(self.config_dir, target_config_name)

        with open(target_path, 'r') as f:
            config = yaml.safe_load(f)

        # Update with best parameters
        print(f"\n>>> Overwriting {target_config_name} with best parameters...")
        config['trainer']['lr_g'] = self.best_config['lr']
        config['trainer']['lr_d'] = self.best_config['lr']
        config['model']['latent_dim'] = self.best_config['latent_dim']
        config['model']['embedding_dim'] = self.best_config['embedding_dim']
        config['model']['generator_channels'] = self.best_config['g_channels']
        config['model']['discriminator_channels'] = self.best_config['d_channels']

        class CleanDumper(yaml.SafeDumper):
            def represent_data(self, data):
                if isinstance(data, list):
                    return self.represent_sequence('tag:yaml.org,2002:seq', data, flow_style=True)
                return super().represent_data(data)
        with open(target_path, 'w') as f:
            yaml.dump(config, f, Dumper=CleanDumper, sort_keys=False, default_flow_style=False)
        print(f">>> {target_config_name} updated successfully.")

if __name__ == "__main__":
    tuner = HyperParameterTuner()
    #tuner.random_search(num_trials=3)
    tuner.grid_search()
    tuner.print_summary()
    tuner.save_best_config()