import os
import random
import pandas as pd
import yaml
import subprocess
import datetime as datetime

class HyperParameterTuner:
    def __init__(self):
        self.script_dir = os.path.dirname(os.path.abspath(__file__))
        self.root = os.path.dirname(self.script_dir)
        self.config_dir = os.path.join(self.root, "config")
        os.makedirs(self.config_dir, exist_ok=True)

        self.results = []
        self.best_config = None
        self.min_g_loss = float('inf')

    def run_experiment(self, params, name):
        tuning_epochs = 1
        temp_file_name = f"temp_tuner_{name}.yaml"
        temp_file_path = os.path.join(self.config_dir, temp_file_name)
        base_path = os.path.join(self.config_dir, 'improved_config.yaml')
        with open(base_path, 'r') as f:
            config = yaml.safe_load(f)

        config['project_name'] = name
        config['trainer'].update({
            'lr_g': params['lr'],
            'lr_d': params['lr'],
            'beta1': params['beta1'],
            'beta2': params['beta2'],
            'epochs': tuning_epochs
        })
        config['model'].update({
            'leaky_slope': params['leaky_slope'],
            'latent_dim': params['latent_dim'],
            'generator_channels': params['g_channels'],
            'discriminator_channels': params['d_channels']
        })
        config['logger']['log_dir'] = f"results/tuning/{name}/logs"

        with open(temp_file_path ,'w') as f:
            yaml.dump(config, f)
            print(f"\n[Tuner] Running: {name} | Params: {params}")
            subprocess.run(["python", "main.py", "--config", temp_file_path], cwd=self.root)

            # 3. Collect Results (Read the CSV generated by main.py)
            csv_path = os.path.join(self.root, config['logger']['log_dir'], 'history.csv')
            if os.path.exists(csv_path):
                df = pd.read_csv(csv_path)
                # We evaluate "best" based on the final epoch's generator loss or stability
                final_g_loss = df['loss_g'].iloc[-1]
                params['final_g_loss'] = final_g_loss
                self.results.append(params)

                if final_g_loss < self.min_g_loss:
                    self.min_g_loss = final_g_loss
                    self.best_config = params

            if os.path.exists(temp_file_path):
                os.remove(temp_file_path)
    def print_summary(self):
        print("\n" + "=" * 50)
        print("TUNING SUMMARY")
        print("=" * 50)
        for i, res in enumerate(self.results):
            print(
                f"Trial {i}: G_Loss: {res.get('final_g_loss', 'N/A'):.4f} | LR: {res['lr']} | Slope: {res['leaky_slope']}")

        if self.best_config:
            print("\n>>> BEST CONFIGURATION FOUND:")
            print(self.best_config)
        print("=" * 50)

    def grid_search(self):
        lrs = [0.00001, 0.0001, 0.0002, 0.001]  # 10^-5 to 10^-3
        beta1_vals = [0.5, 0.9]
        slopes = [0.01, 0.1, 0.2]
        latent_dims = [100, 128]
        for lr in lrs:
            for b1 in beta1_vals:
                for slope in slopes:
                    for l_dim in latent_dims:
                        # Start with default template
                        params = self._get_default_params()

                        # Update with current grid point
                        params.update({
                            'lr': lr,
                            'beta1': b1,
                            'leaky_slope': slope,
                            'latent_dim': l_dim
                        })

                        # Create a unique name for this experiment
                        name = f"grid_lr{lr}_b{b1}_s{slope}_dim{l_dim}"

                        self.run_experiment(params, name)

    def random_search(self, num_trials=5):
        print(f"\n>>> Starting Random Search with {num_trials} trials...")

        # Define some architectural variations to sample from
        channel_options = [
            # Standard [512, 256, 128, 64]
            {'g': [512, 256, 128, 64], 'd': [64, 128, 256, 512]},
            # Slimmer [256, 128, 64, 32]
            {'g': [256, 128, 64, 32], 'd': [32, 64, 128, 256]},
            # Deeper/Wider middle layers
            {'g': [1024, 512, 256, 128], 'd': [128, 256, 512, 1024]}
        ]

        for i in range(num_trials):
            # Sample using Log-Uniform for LR (crucial for finding order of magnitude)
            lr = 10 ** random.uniform(-5, -3)  # Range: 0.00001 to 0.001

            arch = random.choice(channel_options)

            params = {
                'lr': lr,
                'beta1': random.uniform(0.1, 0.9),  # Wide range for momentum
                'beta2': random.uniform(0.9, 0.999),
                'leaky_slope': random.uniform(0.01, 0.3),  # From almost zero to very leaky
                'latent_dim': random.choice([64, 100, 128, 256]),
                'g_channels': arch['g'],
                'd_channels': arch['d']
            }

            trial_name = f"random_trial_{i}_lr{lr:.6f}_slope{params['leaky_slope']:.2f}"

            self.run_experiment(params, trial_name)

    def _get_default_params(self):
        return {
            'lr': 0.0002, 'beta1': 0.5, 'beta2': 0.999,
            'leaky_slope': 0.2, 'latent_dim': 100,
            'g_channels': [512, 256, 128, 64], 'd_channels': [64, 128, 256, 512]
        }

if __name__ == "__main__":
    tuner = HyperParameterTuner()
    #tuner.random_search(num_trials=3)
    tuner.grid_search()
    tuner.print_summary()